"""
skills/loader.py
Discovers and loads skills from skills/library/<name>/{SKILL.md, impl.py}
instead of requiring every skill to be a hand-written @skill(...)-decorated
Python function scattered across large files. Each skill now lives in its
own small folder:

  skills/library/insert_formula/
    SKILL.md   - human- and AI-readable metadata: name, category,
                 description, and the JSON input_schema, all in one place
    impl.py    - the actual implementation: a single run(**kwargs)
                 function plus whatever imports/helpers it needs

SECURITY MODEL - impl.py is real, executable Python that runs with full
access to the live Excel session and this machine's file system. A skill
folder is a code-execution surface, not inert data, even though SKILL.md
looks like harmless documentation. To stop a dropped-in or tampered
folder from being silently loaded and executed:

  - Every skill folder must be listed in skills/library/_manifest.json,
    generated by tools/generate_skill_manifest.py. A folder that exists
    on disk but isn't in the manifest is skipped, not loaded - adding a
    new skill is a deliberate, reviewed action (regenerate the manifest),
    not something that happens just because a file appeared in the folder.
  - The manifest pins a SHA-256 hash of both SKILL.md and impl.py for
    each skill. If either file's contents don't match its pinned hash at
    load time, that skill is refused and logged loudly - this catches
    both tampering and simply forgetting to re-run the manifest generator
    after a real, legitimate edit (the fix in that case is just to
    regenerate it).
  - Nothing here is silent. A missing/tampered/unlisted skill is logged
    as an ERROR or WARNING at startup, not discovered later as a
    confusing "the AI says this skill doesn't exist" bug report.
"""

import hashlib
import importlib.util
import json
import logging
import os
import re

from skills.base import SKILL_REGISTRY

logger = logging.getLogger("skills.loader")

LIBRARY_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "library")
MANIFEST_PATH = os.path.join(LIBRARY_DIR, "_manifest.json")

_FRONTMATTER_RE = re.compile(r"^---\n(.*?)\n---\n", re.DOTALL)
_JSON_BLOCK_RE = re.compile(r"```json\n(.*?)\n```", re.DOTALL)


def _sha256_of(path: str) -> str:
    with open(path, "rb") as f:
        return hashlib.sha256(f.read()).hexdigest()


def _parse_frontmatter(md_text: str) -> dict:
    m = _FRONTMATTER_RE.match(md_text)
    if not m:
        raise ValueError("SKILL.md is missing a --- frontmatter block")
    fm = {}
    for line in m.group(1).splitlines():
        if ":" not in line:
            continue
        key, _, value = line.partition(":")
        fm[key.strip()] = value.strip().strip('"')
    return fm


def _parse_input_schema(md_text: str) -> dict:
    m = _JSON_BLOCK_RE.search(md_text)
    if not m:
        raise ValueError("SKILL.md is missing a ```json input schema block")
    return json.loads(m.group(1))


def _load_manifest() -> dict:
    if not os.path.exists(MANIFEST_PATH):
        logger.warning(
            "skills/library/_manifest.json not found - NO skills will be loaded from "
            "the library folder. Run tools/generate_skill_manifest.py."
        )
        return {}
    with open(MANIFEST_PATH, "r", encoding="utf-8") as f:
        return json.load(f)


def load_all():
    """Loads every manifest-approved skill from skills/library/ into
    SKILL_REGISTRY. Call once, at import time (see skills/__init__.py)."""
    manifest = _load_manifest()
    if not os.path.isdir(LIBRARY_DIR):
        return

    on_disk = {
        name for name in os.listdir(LIBRARY_DIR)
        if os.path.isdir(os.path.join(LIBRARY_DIR, name))
    }
    unlisted = on_disk - set(manifest.keys())
    if unlisted:
        logger.warning(
            "Skill folder(s) found on disk but NOT in _manifest.json - refusing to "
            "load them for safety: %s. If legitimate, run "
            "tools/generate_skill_manifest.py to add them.", sorted(unlisted)
        )

    loaded, refused = [], []

    for name, entry in manifest.items():
        folder = os.path.join(LIBRARY_DIR, name)
        md_path = os.path.join(folder, "SKILL.md")
        impl_path = os.path.join(folder, "impl.py")

        if not (os.path.isfile(md_path) and os.path.isfile(impl_path)):
            logger.error("Manifest lists '%s' but SKILL.md/impl.py is missing - refusing to load.", name)
            refused.append(name)
            continue

        if _sha256_of(md_path) != entry.get("sha256_skill_md"):
            logger.error("'%s' SKILL.md hash mismatch (edited without regenerating "
                         "the manifest, or tampered) - refusing to load.", name)
            refused.append(name)
            continue
        if _sha256_of(impl_path) != entry.get("sha256_impl"):
            logger.error("'%s' impl.py hash mismatch (edited without regenerating "
                         "the manifest, or tampered) - refusing to load.", name)
            refused.append(name)
            continue

        try:
            with open(md_path, "r", encoding="utf-8") as f:
                md_text = f.read()
            frontmatter = _parse_frontmatter(md_text)
            input_schema = _parse_input_schema(md_text)

            if frontmatter.get("name") != name:
                logger.error("'%s' folder name doesn't match SKILL.md frontmatter "
                             "name ('%s') - refusing to load.", name, frontmatter.get("name"))
                refused.append(name)
                continue

            spec = importlib.util.spec_from_file_location(f"skills.library.{name}.impl", impl_path)
            module = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(module)

            if not hasattr(module, "run"):
                logger.error("'%s' impl.py has no run() function - refusing to load.", name)
                refused.append(name)
                continue

            SKILL_REGISTRY[name] = {
                "func": module.run,
                "description": frontmatter.get("description", ""),
                "input_schema": input_schema,
                "category": frontmatter.get("category", "general"),
            }
            loaded.append(name)
        except Exception as e:
            logger.error("Failed to load skill '%s': %s", name, e)
            refused.append(name)

    logger.info("Skill library: loaded %d skill(s), refused %d.", len(loaded), len(refused))
    if refused:
        logger.warning("Refused skills (see errors above): %s", refused)
